on: 
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Release notes'
        required: true
        type: string
        
jobs:
  windows-tests:
    runs-on: windows-2019
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        path: "vpn-client-src"
        submodules: recursive

    - name: Run tests
      shell: cmd
      run: |
          "vpn-client-src\untitled25.exe" 1 || exit /b %errorlevel%
          "vpn-client-src\untitled25.exe" 0 || exit /b %errorlevel%
          "Echo Finish"
