on: 
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Release notes'
        required: true
        type: string
        
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Release notes: ${{ github.event.inputs.release_notes }}" 