on: 
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Release notes'
        required: true
        type: string
        
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "release.tar.gz,*.txt"
        bodyFile: "body.md"
        token: ${{ secrets.GITHUB_TOKEN }}