on: 
  workflow_dispatch:
    inputs:
      release_notes:
        description: 'Release notes'
        required: true
        type: string
        
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    
    - name: Build project
      run : |
        echo "Hello world"
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false